# Tag 1 - XY

## Porta Westfalica
Unsere Exkursion startete am Montag den 13. September 2021 gegen 08:00 am Rundbau des geographischen Instituts (verlinken: https://geographie.uni-koeln.de/institut/gebaeude/rundbau) der Universität zu Köln. Nach Beladen des gemieteten Vans (Busses) ging die Reise in Richtung Minden los. Dort lag mit der Porta Westfalica der erste Zwischenstopp unserer zweiwöchigen Exkursion. Auf dem Weg von Köln nach Minden durchquerten wir das nördliche Sauerland sowie den Teutoburger Wald und kamen vormittags am Kaiser-Wilhelms-Denkmal (verlinken: https://kaiser-wilhelm-porta.de/ https://www.kaiser-wilhelm-denkmal.lwl.org/de/) in Porta Westfalica an. Das Denkmal wurde 1896 nach vier jähriger Bauzeit fertig gestellt und zeigt Wilhelm Friedrich Ludwig von Preußen (1797 – 1988), König von Preußen sowie Deutscher Kaiser. Mit einer Gesamthöhe von knapp 90 m und der erhöhten Lage auf dem Wittekindsberg überwacht das Denkmal den Weserdurchbruch zwischen dem westlich gelegenen Wiehengebirge und dem östlichen Wesergebirge an der Mittelgebirgsschwelle in die Norddeutsche Tiefebene. Das 7 m hohe bronzene Standbild steht auf einem aus Porta-Sandstein errichteten Sockel und wird durch einen steinernen Baldachin überdacht (Quelle: https://www.kaiser-wilhelm-denkmal.lwl.org/de/denkmal/baugeschichte/). (Bild einfügen)
Die geographische Lage des Ehrendenkmals erlaubte kurze Transportwege für den benötigten Baustoff. Der Porta-Sandstein entstand durch die Diagenese von sandigem Material, welches im Oberen Dogger (Jura) vor rund 168 Mio. Jahren in Randmeerlage sedimentiert wurde. Das Gestein ist durch seine braune Färbung und reiche Textur gekennzeichnet. Je nach Fundort kann das Gestein unterschiedlich stark gebändert und carbonathaltig sein. Die graue bis deutlich rotbraune Färbung entsteht durch verschieden hohe Eisengehalte, die neben carbonatischen und tonigen Bindemitteln für die verhältnismäßig hohe Verwitterungsresistenz des Gesteins sorgt und es damit zu einem beliebten Baumaterial machen (Quelle: Ebel & Ehling 2012). Während der vor etwa 100 Mio. Jahren einsetzenden alpidischen Orogenese kam es zu der Hebung und Aufwölbung der Region. Die ehemals abgelagerten Sedimente werden heute in Sand- und Kiesgruben sowie in Steinbrüchen abgebaut. 
In Tieflagen und den Überflutungsgebieten der Weser überwiegen heute Grundwasser beeinflusste Böden wie beispielsweise Gleye sowie verschiedene Auenböden (Quelle: Elwas). Da die Ausgangsgesteine der Bodenbildung häufig kalkhaltig sind und somit Säureeinträge puffern, überwiegen neutrale Boden pH-Werte. Im Weserbergland sowie im Wiehengebirge dominieren Buchenwälder in unterschiedlichen Vergesellschaftungen beispielsweise mit Waldmeister. Auch Mischwälder mit Erlen oder Eichen können angetroffen werden (Quelle: https://www.wald-und-holz.nrw.de/wald-in-nrw/wuchsgebiete/weserbergland).
