# Tag 2 - Moorgenese - Trinkwassergewinnung

## Bastauwiesenmoor 

Nach einem entspannten Abend in der Wiehnen-Therme sind wir alle gestärkt und motiviert aufgebrochen. Das nächste Ziel des  ersten Tages war das Große Torfmoor in den Bastauwiesen. Die Bastauwiesen durften wir am vorherigen Tag bereits kennenlernen  und bei einem Bier die Aussicht auf diese genießen. Die Anfahrt am nöchsten Morgen auf der Moorbadstraße entlang des  Mittellandkanals war durch leichte Nebelschleier geprägt und ließ Vorfreude auf die uns bevorstehende Moorwanderung aufkeimen. Wir starteten am Wanderparkplatz "Großes Torfmoor P3" und konnten nach etwa 5 Minuten den ersten Blick auf das im Morgentau und -frost liegenden Hochmoor erlanden. Besonders hervorgestochen sind  vielen Spinnennetzen die von den Spinnentieren flächendeckend verteilt in der Moorvegetation gesponnen wurden. Der morgentliche Tau verfing sich in der Seide der kunstvollen Netze, wudurch eine besonders mystische Atmosphäre geschaffen wurde. 

Auf einem aus Holz erbauten Aussichtsturm konnten wir einen weiten Blick in das 606 ha große Naturschutzgebiet erhalten. Das Moor gehört zu den Bastauwiesen und bildet zusammen mit zwei weiteren Mooren eine ausgedehnte Moorniederungslandschaft entland des Mittellandkanals zwischen Minden und Lübbecke. Der hiesige Grundwasserstand liegt bei 40 cm. Betreut wird das Naturschutzgebiet von der [Biologischen Station Minden-Lübbecke e.V.](https://biostation-ml.de). Sie planen und verwirklichen die nötigen Naturschutzmaßnahmen, erfassen die gegebene Flora und Fauna und sorgen somit zu einem langfristigen Erhalt des Moores. Damit die Moorlandschaft nicht durch die dort verbreiteten Erlen und Birken verbuscht, ist es wichtig, dass regelmäßige Rodungsarbeiten durchgeführt werden. test
