# Tag 3 - XY

## Forstliche Dauerbeobachtungsfläche Augustendorf
<div style="text-align: justify">

Am 3. Tag brachen wir nach einer ruhigen Nacht im [Jugendhof Vechta](https://www.bdkj-jugendhof.de/) und dem gemeinsamen morgendlichen Frühstück sowie der Erkentnis, dass Lunchpakete in Jugendherbergen in Bezug auf das Preis-Leistungs-Verhältnis ein eher schlechter Deal sind, auf in Richtung der forstlichen Dauerbeobachtungsfläche Augustendorf. Die Fläche wird durch die [Nordwestdeutsche Forstliche Versuchsanstalt (NW-FVA)]( https://www.nw-fva.de/) betreut und unterliegt der Level II. Grundsätzlich werden im Forstlichen Umweltmonitoring folgende Kategorien unterschieden (Dammann et al., 2020):

-	waldflächenrepräsentative Übersichtserhebungen auf einem systematischen Stichprobenraster (Level I), 

-	die **intensive Dauerbeobachtung** ausgewählter Waldökosysteme im Rahmen verschiedener Beobachtungsprogramme (Bodendauerbeobachtungsprogramm (BDF), **Level II**, Waldökosystemstudie Hessen (WÖSSH)) 

-	sowie Experimentalflächen, z. B. Vergleichsflächen zur Bodenschutzkalkung (Level III).
 

## Torfwerk
<div style="text-align: justify">


## Bad Zwischenahner Meer
<div style="text-align: justify">
