# Tag 5 - XY

## Besuch der Aluminiumoxid-werke Stade

Nachdem sich die Gruppe schweren Herzens von ihrem Hotel in Bremen verabschiedet hatte, ging es nun wieder aus der großen Stadt richtung Nordosten an die Niedersächsiche Elbküste.

Hier tauchte unsere Exkursionsgruppe in die Welt der Schwerindustrie ein, bei einem besuch der Aluminiumoxidwerke in Stade.
Die gleichnamige Firma wurde 1973 gegründet und ist mittlerweile der einzig verbliebene Großhersteller von Aluminiumhydroxid und Aluminiumoxid.

Bei der Führung übers werksgelände durch Herrn xxx bekam die Gruppe dabei einen Einblick in den gesamten produktionsprozess, vom Bauxit zum fertigen Aluminiumoxid.

Der Fertigungsprozess beginnt an der Elbeküste im Werkseigenen Hafen. Das Bauxit das hier ankommt stammt von Tagebauen in den Tropen mittlerweile großteils aus Australien. Bei Bauxit handelt es sich um ein gestein beziehungsweise eine Bodenform die einen Besonders hohen Aluminiumanteil aufweist. Zwar ist Aluminium eines der häufigsten Elemente auf der Erden, jedoch ist dessen Anteil in Silikatgesteinen relativ gering während er bei Bauxit auf bis zu 50% kommt, wedurch die Aluminiumgewinnung erst rentabel wird.
Die Lage an der Elbe ist dabei entscheidend für das Werk, da der transport von schwerlasten wie Bauxiterde auf Hochseeschiffen um ein vielfaches günstiger ist als über Land. Schätzungsweise wäre selbst der Transport von Rotterdam nach Stade des Bauxits per Lastwagen genauso teuer wie der gesamte vorangegangene Transport per Schiff um die halbe Welt. Das Bauxit wird nach dem Transport über Förderbänder dann im Bayerverfahren unter Druck und hohen Temperaturen mit Natronlaufe versetzt. Dadurch löst sich das Aluminiumoxid im Erz und bindet sich an das Natrium. Daraufhin wird die Lösung mit fertigem Aluminiumhydroxid "geimpft", wodurch kristallisationkeime enstehen an den sich das Aluminiumhydroxid nach und nach ausfällen kann.
Im Anschluss kann das Aluminiumhydroxis in Hochöfen gebrannt werden um den Wasserstoff loszuwerden und Aluminiumoxid zu erzeugen. Da es jedoch in der Industrie auch vielfältige anwendungen für das Hydroxid gibt ist dies nicht bei der gesamten Produktionsmenge nötig.
Ursprünglich verfügte das Werk auch über Produktionshallen in denen durch Elektrolyse das Aluminiumoxid zu reinem Aluminium verarbeitet wurde. Dieser Prozess ist jedoch extrem Energieaufwendig und lohnt sich nur an Standorten an denen der Strom extrem billig ist, weshalb dieser produktionschritt in Stade schon vor längerem aufgegeben wurde.
Eine Orientierung zum immensen Energieaufwand bietet ein Blick auf die Weltmarktpreise: Der Preis für Aluminiumoxid beträgt meist nur 12 bis 14 prozent des Aluminiumpreises was bedeutet das Strom im 7-fachen Wert des ausgangsproduktes verwendet werden muss um Aluminiumoxid zu Aluminium zu verarbeiten. Entsprechend findet die Produktion mittlerweile in Island oder in Ölstaaten statt.
Von Anfange bis Ende kann man aus 4 Tonnen Bauxit etwa 2 Tonnen Aluminiumoxid gewinnen, und eine Tonne Aluminium. Dementsprechend fällt eine Menge Abfallprodukte bei der produktion an. Dieser wird gemeinhin als "Rotschlamm" bezeichnet und wird oft als Umweltrisiko gesehen, besonders in Ländern des globalen Südens in denen die Entsorgung problematisch ist. Diese Gefahr geht jedoch hauptsächlich von der Natronlauge aus. In den Werken in Stade wird die Natronlauge herausgefiltert,und übrig bleibt ein roter staub der hauptsächlich aus Metallverbindungen besteht. Diese lagern auf der nahegelegenen Deponie und sind komplett Wasserunlöslich und stellen so kein Umweltrisiko dar, müssen jedoch vor verwehung geschützt werden