# Tag 9 - Gutsanlage Panker, Steilküste, Windpark

## Gutsanlage Panker

<div style="text-align: justify">
Am neunten Tag unserer Reise besuchen wir zuerst die [Gutsanlage Panker](https://www.gutpanker.de). Diese liegt liegt im Kreis Plöhn bei Lütjenburg in Ostholstein. Die Anlage wird derzeit von Heinrich Donatus Prinz von Hessen verwaltet. Landarbeiter lebten hier unter ärmlichen Bedingungen auf den Gütern. Im Gegensatz zur Geest und zur Marsch sind hier viele adelige Güter gewesen. Diese haben sich hier im 14. Jahrhundert dieses Gutswesen errichtet. Die Güter waren 300 bis 400 Hektar groß, manchmal auch zwischen 500 und 800 Hektar, und hatten oft neben den Gütern sogenannte Meierhöfe, so dass, wenn man dieses Gut hatte, plus 4 oder 5 Meierhöfe, sich die Anlage auf teilweise zweieinhalbtausend Hektar fruchtbares Land erstreckte. Teilweise war das Land auch an Landwirte verpachtet. Auf dem Gut waren keine eigenständigen Bauern und Ende 1700 fing Graf Rantzau damit an, das Gut in feste Bauernhand zu vergeben, weil er merkte, dass die Pächter auf den Höfen nicht so gut wirtschafteten. Auch wurden dort die Parzellen dort eingezäunt. Dies nennt man Verkoppelung. 

Diese Güter waren sogenannte Gutsbezirke bzw. Verwaltungsbezirke. Es gab keine Gemeinden, sondern der Gutsherr, Baron, von, oder Graf, stand einem Gutsbezirk vor. Die Gutsbezirke wurden erst 1937 abgeschafft und in Gemeinden überführt, und der Gutsbezirksvorsteher, der Adlige, war mit vielen Rechten ausgestattet. Mit dem Ersten Weltkrieg wurde die Macht der Adeligen jedoch gebrochen.

Um 1924 gab es die sogenannten Siedlungsreform, wo man den Gütern das Land, was sie an die Bauern verpachtet hatten, wegnahm. Die Bauern wurden daraufhin eigenständig. Sie mussten langfristige Kredite zahlen. Nach dem zweiten Weltkrieg kamen viele Flüchtlinge ins Land, auch viele Landwirte aus Ostpreußen und Pommern über die Ostsee geflüchtet. Diese hatten kaum Besitz. So gab es nach dem Zweiten Weltkrieg eine zweite große Siedlungsreform, wodurch die Güter massiv verkleinert wurden. In Ostdeutschland wurden sie hingegen von den Russen enteignet. 

Die landwirtschaftlichen Betriebe waren ca. 35 bis 40 Hektar groß, was im Vergleich zu anderen Teilen Deutschlands (z.B. Baden-Württemberg) immer noch viel war. Heute sind sie nicht mehr überlebensfähig. Sie sind in den letzten 30 Jahren verschwunden. Die Landwirte haben es gepachtet oder die alten Besitzer wurden verdrängt bzw. die Industrie kaufte sich hier ein. Die bäuerliche Landwirtschaft ist somit fast so gut wie ausgestorben. Auch das sogenannte „Landgrabbing“ sei hier schon vorzufinden. 

</div>

