# Tag 10 - XY

Am 10. Tag brach die Gruppe frühmorgens ihr Lager in der Bundeswehrkaserne ab und machte sich auf den weiten weg nach Mecklenburg in den Strandort Warnemünde. Die Landschaft die auf der Fahrt durchquert wurde war dabei der Hauptstar des Tages.
Die Straßen die der Kleinbus unserer Gruppe entlangfuhr schlängelten sich durch Hügelige Landschaften mit üppigen Feldern und grünen Weiden, wie man sie sonst aus Werbeprospekten des Voralpenlandes gewohnt ist. Das vorfinden einer solchen Landschaft im eigentlich für seine weiten Horizonte bekannte Norddeutschland mag zunächst verwundert, ein Blick in die vergangenheit sorgt jedoch für Erklärung. Die Holsteinsche Schweitz ist nämlich genau wie das Alpenvorland eine Jungmoränenlandschaft aus der letzten Kaltzeit, der Würm bzw. Weichselkaltzeit. 

## Überblick glaziale Serie

Ganz Nordeutschland, beziehungsweise die sehr bezeichnende Norddeutsche Tiefebene, ist durch die Gletscher der letzten großen Kaltzeiten geprägt. Von Skandinavien kommend rollten sich dabei kilometerdicke gletscherzungen über das land, welche sämtliche Bodenschichten bis auf das Grundgestein wegschleiften. Deshalb kann man Erdgeschichlich auch nur bis in die letzten drei Eiszeiten blicken, die Weichsel, Saale und Elster- Kaltzeiten. Die Böden sind  daher auch durch die glazialen und periglazialen prozesse dieser Zeit geprägt und bestehen aus dem von den Gletschern mitgetragenem Gestein (Geschiebemergel) in verschiedenen Erosionsstadien. Nun stießen die Gletscher der Weichselkaltzeit allerdings lange nicht so weit vor wie die der vorangegangen Saale-Eiszeit (siehe Karte). Bei ihrem zurückschmelzen am Ende der Weichselkaltzeit vor etwa 12.000 Jahren hinterlassen sie daher die aufgeschütteten Endmoränen und die Spuren ihrer Schmelzwasserflüsse, wodurch sich das östliche Hügelland in Schleswig Holstein gebildet hat.

## Landschaft und Ackerbau

Die hinterlassenen spuren der Gletscher können relativ komplex entstanden sein. So auch der Bungsberg, mit 167,4 metern der höchste Hügel schleswig-Holsteins. Dieser geht vermutlich auf eine Saalezeitliche Endmoräne zurück, welche dann in der Weichselzeit von den nachfolgenden gletschern umflossen wurde. Der Wissenschaftliche Begriff hierfür ist "Nunatak" was aus dem Grönländischen stammt.

Die Gruppe machte hier einen längeren halt und bestaunte die Aussicht. Dies war auch der Moment an dem die Gruppe ein für alle mal vom Flachland das sie die letzten 10 Tage begleitet hatte Abschied nahm.

## Toteisloch

Die letzte Station im östlichem Hügelland war ein kleiner See umgeben von steilen hängen der ihn umschließenden Hügel. Auch hierbei handelt es sich um eine glaziale Form der späten Weichselzeit, ein Toteisloch. Ein solches entsteht wenn beim Rückzug der Gletscher einzelne Eisflächen, meist in einer Mulde vom Hauptgletscher abgeschnitten werden. Eine solche Eisfläche kann nicht mehr mit neuem Material versorgt werden, wodurch sie zum bezeichneten "Toteis" wird. Oftmals folgt darauf die Überschüttung einer solchen Eisfläche mit Sedimenten, was ein abschmelzen durch Sonneneinstrahlung verhindert. Das Toteis kann dann über Jahrhunderte oder Jahrtausende im Untergrund verbleiben. Wenn es letztendlich abschmilzt entsteht ein Hohlraum im Untergrund welcher früher oder später einstürzt. Die entstandene Toteisloch füllt sich mit Grundwasser und es eintsteht ein See. Da dieser Prozess im Periglazialem Raum keine seltenheit ist, sind Toteislochseen in Jungmoränengebieten wie der Holstein'schen Schweiz häufig vorzufinden.