# Tag 11 - Fischland-Darß-Zingst

## Fischland-Darß-Zingst (Jana)

<div style="text-align: justify">

Für den heutige Tag ist eine Wanderung über die küstenmorphologisch interessante Halbinsel Fischland-Darß-Zingst innerhalb des Nationalparks Vorpommersche Boddenlandschaft geplant.
**Fischland und Morphologie beschreiben...**
**Im Holozän umgelagert, Ausgleichsküste, Nährung, Bodden und Boddenküste, Verbohrung...**
**Ackerbau nicht möglich, Mastvieh oft extensiv, Künstlerkolonien...**
Da recht stürmisches Wetter angesagt ist, packen wir unsere Regenkleidung ein und machen uns darauf gefasst unsere Wanderung frühzeitig abbrechen zu müssen. Von unserer Unterkunft aus fahren wir in Richtung Nordosten und starten unseren Fußweg zum Leuchtturm Darßer Ort von Prerow aus. Wir durchwandern den Darßwald oder auch Darßer Wald, der zu großen Teilen nicht bewirtschaftet wird und dementsprechend sehr naturbelassen ist. 

</div>

## Stralsund (Julia)

<div style="text-align: justify">
Im Anschluss an die windige und zunehmend regnerische Wanderung freuten wir uns über die Rückkehr in unseren warmen Bus und fuhren weiter in die Hansestadt Stralsund, die durch ihre Lage an der Meerenge Strelasund im Volksmund oft als *Tor zur Insel Rügen* bezeichnet wird (Tourismuszentrale Rügen 2022). Statt auf die Brücke nach Rügen fuhren wir zum Schnelltest Drive-in, wo sich einzelne mittlerweile leider erkältete Mitglieder der Gruppe einem - zum Glück negativ ausfallenden - Corona-Abstrich unterzogen. Da die Gruppe von der Wanderung ein leichtes Nachmittagstief einholte, entschieden wir nach einem kurzen stürmischen Spaziergang durch die Stadt, das schlechte Wetter zu nutzen, um Stralsunds Gastronomie-Kultur zu erkunden. Bei Kaffee, Kakao und Kuchen wurde über die Wanderung revidiert und ein wenig durchgeatmet. Kurz danach traf die gesamte Gruppe in einem Kartoffel-Restaurant zusammen, um hier gemeinsam zu Abend zu essen. Nach dem umfangreichen Abendessen in dem Kellergewölbe kam noch eine turbulente Rückfahrt auf uns zu, die durch die starken Windböen auf der dunklen Landstraße einen echten Abenteuercharakter annahm. Die laute Musik und Späße der Gruppenmitglieder hielten aber auch den Fahrer bei Laune, der die Gruppe letztendlich wohlbehalten zurück in die Jugendherberge brachte. 


</div>

**Quellen**

Tourismuszentrale Rügen, 2022. Hansestadt Stralsund. https://www.ruegen.de/ueber-ruegen/inselorte/suedruegen/stralsund/, 2022-01-27. 