# Tag 12 - Ivenacker Eichen, Arendsee

## Arendsee

<div style="text-align: justify">
Nach dem Besuch der Ivenacker Eichen geht es zum Arendsee in der Region Altmark in Sachsen-Anhalt. Dort machen wir direkt am Ufer halt, mit gutem Blick auf den See. Hier erzählt uns Kristof etwas über die Entstehung des Sees.

Entstanden ist der See durch das Schmelzen der Gletscher, sodass das Zechsteinmeer vordringen konnte. Durch Flutung wird dieses „Becken“ abgeschnitten oder es kommt durch eine Regression wieder. Beim Rückzug des Wassers bleibt schließlich eine Pfütze in diesem Becken übrig. 
„Wenn man Salz in einen Kochtopf gibt, verkocht es, und am Ende bleibt eine Salzkruste die dann wieder verdampft und die Salze bleiben übrig“.

Ähnlich ist es beim Zechsteinmeer gewesen. Man hat einen Zustrom, sinkt der globale Meeresspiegel, dann kann dieser Zufluss auch unterbrochen werden. Und man hat ein abgeschlossenes Becken, ähnlich wie der Bodden oder wie die Ostsee oder das Mittelmeer. An der Straße von Gibraltar war es auch irgendwann mal geschlossen, so dass das Mittelmeer keinen Zufluss zum Atlantik gehabt hat und auch wie so eine überdimensionale Pfütze gewesen ist. 
Das Wasser verdunstet und die gelösten Ionen im Wasser, wie zum Beispiel Natrium, Kalium, Chlorid oder Sulfat reichern sich an, wenn das Wasser verdunstet, und irgendwann wird ein Löslichkeitsprodukt überschritten. Dann kommt es dazu, dass sich in einer bestimmten Abfolge Salze und Minerale bilden. Und das nennt man eine „Saline-Serie“, eine „Folge“ oder eine „Salinare“. Das beschreibt eine Abfolge, wie sie für die Zechsteinabfolge charakteristisch ist. 

Wenn die Sedimentationsgeschwindigkeit abgesetzt wird, bilden sich feinkörnige Tone. Ganz feinkörnige Sedimentsteine, Tonsteine. Als nächstes fallen die Carbonate aus, also Calciumcarbonat oder Dolomit. Dolomit ist ein Magnesium Karbonat. Sind extrem schlecht wasserlöslich (wenige Milligramm pro Liter sind nur wasserlöslich, 14 Milligramm pro Liter).

Als nächstes in der Salinen-Serie würden Sulfat Verbindungen ausfallen, z.B. Gips. Das ist die wasserreiche Variante. Und Anhydrit, das ist die wasserfreie Variante. Also hat man Tone, Karbonate, dann die Sulfate. Und als letztes würden sich die Edelsalze bilden (z.B. Steinsalz, Natriumchlorid, Kochsalz, oder Kaliumchlorid). Somit findet man in Norddeutschland bis zu 2.000 Meter mächtige Zechsteinabfolgen von Salzen. 

Die Erdgeschichte ist sehr komplex. Der Gletscher kann auch wieder schmelzen, sodass es wieder eine neue Transgression gibt und die Salinare unterbrochen wird. Es kommt wieder neues Wasser dazu, dann zieht sich das wieder zurück, es bildet sich etwas Neues darüber. Dieses Vorstoßen und Rückstoßen des Meeres kann man grob in sieben Zyklen innerhalb dieser Zechsteinphase unterscheiden. Manchmal sind diese Folgen nicht mustergültig ausgeprägt, beispielsweise findet man vielleicht nur ein paar bestimmte Folgen, dann werden diese vielleicht komplett wegerodiert. Salze sind wasserlöslich, also können diese auch wieder gelöst und verlagert werden.  

Das Zechstein ging circa 7 Millionen Jahre, (relativ kurze Zeiteinheit nur gewesen aber sehr prägend und intensiv) 257 bis 251 Millionen Jahre before Matjes! ;-)

Salz hat in besonders hohen Tiefen (wenn viel Druck darauf liegt) die Eigenschaft sehr zähplastisch zu werden, weil es eine geringere Dichte hat als zum Beispiel die Sedimente, die da drüber liegen. Es neigt dann dazu, sich den Weg, wenn viel Druck drauf ist, nach oben zu bahnen. Beim Arendsee ist es so, dass die Salze sich den Weg in den Untergrund suchen (man hat über diesen Salzen noch ein Deckgebirge und nach der letzten Vereisung hier viel Schmelzwasser, groß angelegte Seen)

In Süddeutschland gibt es Karstgrundwasserleiter. Grundwassersysteme die sehr schnellzügig sind. Hier dauert das ein bisschen, bis das Grundwasser in Kontakt mit den Salzschichten kommt (Subrosion genannt). So entstehen große Hohlräume im Untergrund, was dann hier dazu geführt hat, dass das Deckgebilde einstürzt und so eine riesen Hohlform gebildet hat, mit sehr steilen Flanken.

Nach diesen interessanten Inforamtionen, die uns Kristof mit auf den Weg gibt, geht es zurück zum Auto, und damit auch zurück nach Hause.


Quellen:

B. Nixdorf, M. Hemm, A. Hoffmann & P. Richter, 2003: Dokumentation von Zustand und Entwicklung der wichtigsten Seen Deutschlands. Teil 7: Sachsen-Anhalt. Umweltforschungsplan des Bundesministeriums für Umwelt, Naturschutz und Reaktorsicherheit, Abschlussbericht F&E Vorhaben FKZ 299 24 274.

Arv08. Abrufbar unter: https://www.arv08.de/verein/segelrevier-umgebung/

</div>
