# Samstag, 25.09.2021

Abfahrt: Jugendherberge Hitzacker

Ankunft: Köln

<div style="text-align: justify">

Nach unserer finalen Exkursionsnacht und einer morgendlichen Stärkung am Frühstücksbuffet in der Jugendherberge Hitzacker, ging es für uns ein letztes Mal in unser liebgewonnenes Exkursionsmobil. Mit Gepäck, Lunchpacketen und einer etwas wehmütigen Stimmung machten wir es uns bequem und verließen die Norddeutsche Tiefebene in Richtung Heimat. Der erkältete Teil der Exkursionsgruppe durfte freundlicherweise den Beifahrerplatz belegen, sodass sich die weiteren TeilnehmerInnen nicht allzu sehr durch die Nieß- und Hustanfälle gestört fühlen mussten. Diverse Playlists durften beim bislang längsten Fahrabschnitt nicht fehlen und vertrieben die Müdigkeit, der bis auf die beiden Exkursionsleiter jeder und jede in unserem Fahrzeug mehrfach erlegen war.

Den letzten Zwischenstop vor Köln machten wir für eine kurze Toilettenpause an der Raststätte Remscheid. Der hier vollzogene und letzte Fahrerwechsel brachte auch einen sehr entscheidenen Musikwandel mit sich. Denn, den Kölner Dom in Sichtweite, kam was kommen musste - echte kölsche Musik. So erlebnis-, abwechslungs- und lehrreich unsere Exkursion in den Norden Deutschlands auch war, gilt wohl für uns alle "Home is, where the Dom is".

An der Uni angekommen, ging es ans große Putzen. Mit Besen, Putzlappen und Kehrblech bewaffnet, wurde geschrubbt und gekehrt, bis unser Exkursionsmobil wieder rückgabereif aussah. Dabei wurden noch allerlei alte Pfandflaschen entsorgt, die es sich tagelang unter unseren Sitzen gemütlich gemacht und hin und wieder die Mitfahrenden umherrollend zur Weißglut getrieben hatten. Als dies endlich erledigt war, ging es für die Studierenden nach Hause, während Kristof das Exkursionsmobil in einwandfreiem Zustand und mit einigen Kilometern mehr auf dem Tacho zurückbrachte.

**Danksagung**

An dieser Stelle danken wir den vielen interessanten Persönlichkeiten und den Verantwortlichen der besuchten Institutionen, die wir während unserer Reise kennenlernen und besuchen durften. Wir haben Einblicke in extrem vielfältige und spannende Bereiche der Geographie bekommen und unser bisheriges Wissen über die naturräumlichen und wirtschaftlichen Aspekte Norddeutschlands erweitern können.

Ganz besonders gilt unser Dank Herrn Prof. Dr. Tim Mansfeldt und Herrn Dr. Kristof Dorau, die diese Exkursion so umfangreich geplant haben und ohne die unsere Fahrt in der Form nicht möglich gewesen wäre.

Schlussendlich gilt der Dank jedem und jeder ExkursionsteilnehmerIn, die diese Fahrt mit Leben gefüllt haben und einiges an interessanten und unterhaltsamen Geschichten mitbrachten.
</div>